import {
  MdOutlineDataThresholding,
  MdStorage,
  MdAccountTree,
  MdMonitorHeart,
  MdInsights,
  MdAutoGraph,
  MdPsychology,
  MdDashboard,
  MdSettings,
  MdSchedule,
  MdNotificationsActive,
  MdLockOutline,
  MdRuleFolder,
} from "react-icons/md";

export const menuItems = [
  {
    id: "data-extraction",
    title: "استخراج داده",
    link: "/data-extraction",
    icon: MdOutlineDataThresholding,
    submenu: null,
  },
  {
    id: "data-transformation",
    title: "تبدیل و پردازش داده",
    link: "/data-transformation",
    icon: MdSettings,
    submenu: null,
  },
  {
    id: "data-storage",
    title: "بانک داده",
    link: "/data-storage",
    icon: MdStorage,
    submenu: null,
  },
  {
    id: "pipelines",
    link: "/pipelines",
    title: "پایپ‌لاین‌ها",
    icon: MdAccountTree,
    submenu: null,
  },
  {
    id: "monitoring",
    link: "/monitoring",
    title: "مانیتورینگ",
    icon: MdMonitorHeart,
    submenu: null,
  },
  {
    id: "visualization",
    link: "/visualization",
    title: "بصری‌سازی",
    icon: MdAutoGraph,
    submenu: null,
  },
  {
    id: "machine-learning",
    link: "/machine-learning",
    title: "یادگیری ماشین",
    icon: MdPsychology,
    submenu: null,
  },
  {
    id: "business-intelligence",
    link: "/business-intelligence",
    title: "هوش تجاری",
    icon: MdInsights,
    submenu: null,
  },
  {
    id: "general",
    link: "/general",
    title: "عمومی",
    icon: MdDashboard,
    submenu: [
      {
        id: "schedules",
        link: "/schedules",
        title: "زمان‌بندی‌ها",
        icon: MdSchedule,
      },
      {
        id: "notifications",
        link: "/notifications",
        title: "اعلان‌ها",
        icon: MdNotificationsActive,
      },
      {
        id: "access-control",
        link: "/access-control",
        title: "دسترسی‌ها",
        icon: MdLockOutline,
      },
      {
        id: "data-governance",
        link: "/data-governance",
        title: "حاکمیت داده",
        icon: MdRuleFolder,
      },
    ],
  },
];
